/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Color;

/**
 *
 * @author flavi
 */
public class Jogoquatro extends javax.swing.JFrame {
    int erros;
    /**
     * Creates new form Jogoquatro
     */
    public Jogoquatro() {
        initComponents();
        erros = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        jButton1 = new javax.swing.JButton();
        panelImage3 = new org.edisoncor.gui.panel.PanelImage();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        tx8 = new javax.swing.JFormattedTextField();
        tx1 = new javax.swing.JFormattedTextField();
        tx2 = new javax.swing.JFormattedTextField();
        tx3 = new javax.swing.JFormattedTextField();
        tx4 = new javax.swing.JFormattedTextField();
        tx5 = new javax.swing.JFormattedTextField();
        tx6 = new javax.swing.JFormattedTextField();
        tx7 = new javax.swing.JFormattedTextField();
        vd1 = new org.edisoncor.gui.panel.PanelImage();
        vd2 = new org.edisoncor.gui.panel.PanelImage();
        vd3 = new org.edisoncor.gui.panel.PanelImage();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/backjogo.jpg"))); // NOI18N
        panelImage1.setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/voltar.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelImage1.add(jButton1);
        jButton1.setBounds(10, 0, 60, 60);

        panelImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconfilme.png"))); // NOI18N

        javax.swing.GroupLayout panelImage3Layout = new javax.swing.GroupLayout(panelImage3);
        panelImage3.setLayout(panelImage3Layout);
        panelImage3Layout.setHorizontalGroup(
            panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        panelImage3Layout.setVerticalGroup(
            panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        panelImage1.add(panelImage3);
        panelImage3.setBounds(240, 10, 50, 50);

        jPanel1.setBackground(new java.awt.Color(248, 210, 17));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        panelImage1.add(jPanel1);
        jPanel1.setBounds(300, 10, 2, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(251, 225, 0));
        jLabel1.setText("Qual o nome do filme?");
        panelImage1.add(jLabel1);
        jLabel1.setBounds(310, 20, 210, 30);

        panelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/coraline.jpg"))); // NOI18N

        javax.swing.GroupLayout panelImage2Layout = new javax.swing.GroupLayout(panelImage2);
        panelImage2.setLayout(panelImage2Layout);
        panelImage2Layout.setHorizontalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        panelImage2Layout.setVerticalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        panelImage1.add(panelImage2);
        panelImage2.setBounds(140, 130, 460, 250);

        try {
            tx8.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tx8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tx8KeyReleased(evt);
            }
        });
        panelImage1.add(tx8);
        tx8.setBounds(580, 410, 60, 40);

        try {
            tx1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tx1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tx1KeyReleased(evt);
            }
        });
        panelImage1.add(tx1);
        tx1.setBounds(90, 410, 60, 40);

        try {
            tx2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tx2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tx2KeyReleased(evt);
            }
        });
        panelImage1.add(tx2);
        tx2.setBounds(160, 410, 60, 40);

        try {
            tx3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tx3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tx3KeyReleased(evt);
            }
        });
        panelImage1.add(tx3);
        tx3.setBounds(230, 410, 60, 40);

        try {
            tx4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tx4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tx4KeyReleased(evt);
            }
        });
        panelImage1.add(tx4);
        tx4.setBounds(300, 410, 60, 40);

        try {
            tx5.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tx5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tx5KeyReleased(evt);
            }
        });
        panelImage1.add(tx5);
        tx5.setBounds(370, 410, 60, 40);

        try {
            tx6.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tx6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tx6KeyReleased(evt);
            }
        });
        panelImage1.add(tx6);
        tx6.setBounds(440, 410, 60, 40);

        try {
            tx7.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tx7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tx7KeyReleased(evt);
            }
        });
        panelImage1.add(tx7);
        tx7.setBounds(510, 410, 60, 40);

        vd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/vida.png"))); // NOI18N

        javax.swing.GroupLayout vd1Layout = new javax.swing.GroupLayout(vd1);
        vd1.setLayout(vd1Layout);
        vd1Layout.setHorizontalGroup(
            vd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        vd1Layout.setVerticalGroup(
            vd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        panelImage1.add(vd1);
        vd1.setBounds(620, 10, 40, 40);

        vd2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/vida.png"))); // NOI18N

        javax.swing.GroupLayout vd2Layout = new javax.swing.GroupLayout(vd2);
        vd2.setLayout(vd2Layout);
        vd2Layout.setHorizontalGroup(
            vd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        vd2Layout.setVerticalGroup(
            vd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        panelImage1.add(vd2);
        vd2.setBounds(670, 10, 40, 40);

        vd3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/vida.png"))); // NOI18N

        javax.swing.GroupLayout vd3Layout = new javax.swing.GroupLayout(vd3);
        vd3.setLayout(vd3Layout);
        vd3Layout.setHorizontalGroup(
            vd3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        vd3Layout.setVerticalGroup(
            vd3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        panelImage1.add(vd3);
        vd3.setBounds(720, 10, 40, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(788, 658));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        tx2.setVisible(false);
        tx3.setVisible(false);
        tx4.setVisible(false);
        tx5.setVisible(false);
        tx6.setVisible(false);
        tx7.setVisible(false);
        tx8.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void tx1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx1KeyReleased
        if (tx1.getText().equals("C")){
            tx1.setBackground(Color.green);
            tx2.setVisible(true);
            tx2.requestFocus();
        }else{
            tx1.setBackground(Color.red);
            tx1.requestFocus();
            erros +=1;
            if (erros == 1){
            vd1.setVisible(false);
            }
            else if (erros == 2){
            vd1.setVisible(false);
            vd2.setVisible(false);
            }
            else if (erros == 3){
            vd1.setVisible(false);
            vd2.setVisible(false);
            vd3.setVisible(false);
            new Perdeu().setVisible(true);
            dispose();
            }
        }
    }//GEN-LAST:event_tx1KeyReleased

    private void tx2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx2KeyReleased
        if (tx2.getText().equals("O")){
            tx2.setBackground(Color.green);
            tx3.setVisible(true);
            tx3.requestFocus();
        }else{
            tx2.setBackground(Color.red);
            tx2.requestFocus();
            erros +=1;
            if (erros == 1){
            vd1.setVisible(false);
            }
            else if (erros == 2){
            vd1.setVisible(false);
            vd2.setVisible(false);
            }
            else if (erros == 3){
            vd1.setVisible(false);
            vd2.setVisible(false);
            vd3.setVisible(false);
            new Perdeu().setVisible(true);
            dispose();
            }
        }
    }//GEN-LAST:event_tx2KeyReleased

    private void tx3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx3KeyReleased
        if (tx3.getText().equals("R")){
            tx3.setBackground(Color.green);
            tx4.setVisible(true);
            tx4.requestFocus();
        }else{
            tx3.setBackground(Color.red);
            tx3.requestFocus();
            erros +=1;
            if (erros == 1){
            vd1.setVisible(false);
            }
            else if (erros == 2){
            vd1.setVisible(false);
            vd2.setVisible(false);
            }
            else if (erros == 3){
            vd1.setVisible(false);
            vd2.setVisible(false);
            vd3.setVisible(false);
            new Perdeu().setVisible(true);
            dispose();
            }
        }
    }//GEN-LAST:event_tx3KeyReleased

    private void tx4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx4KeyReleased
        if (tx4.getText().equals("A")){
            tx4.setBackground(Color.green);
            tx5.setVisible(true);
            tx5.requestFocus();
        }else{
            tx4.setBackground(Color.red);
            tx4.requestFocus();
            erros +=1;
            if (erros == 1){
            vd1.setVisible(false);
            }
            else if (erros == 2){
            vd1.setVisible(false);
            vd2.setVisible(false);
            }
            else if (erros == 3){
            vd1.setVisible(false);
            vd2.setVisible(false);
            vd3.setVisible(false);
            new Perdeu().setVisible(true);
            dispose();
            }
        }
    }//GEN-LAST:event_tx4KeyReleased

    private void tx5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx5KeyReleased
        if (tx5.getText().equals("L")){
            tx5.setBackground(Color.green);
            tx6.setVisible(true);
            tx6.requestFocus();
        }else{
            tx5.setBackground(Color.red);
            tx5.requestFocus();
            erros +=1;
            if (erros == 1){
            vd1.setVisible(false);
            }
            else if (erros == 2){
            vd1.setVisible(false);
            vd2.setVisible(false);
            }
            else if (erros == 3){
            vd1.setVisible(false);
            vd2.setVisible(false);
            vd3.setVisible(false);
            new Perdeu().setVisible(true);
            dispose();
            }
        }
    }//GEN-LAST:event_tx5KeyReleased

    private void tx6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx6KeyReleased
        if (tx6.getText().equals("I")){
            tx6.setBackground(Color.green);
            tx7.setVisible(true);
            tx7.requestFocus();
        }else{
            tx6.setBackground(Color.red);
            tx6.requestFocus();
            erros +=1;
            if (erros == 1){
            vd1.setVisible(false);
            }
            else if (erros == 2){
            vd1.setVisible(false);
            vd2.setVisible(false);
            }
            else if (erros == 3){
            vd1.setVisible(false);
            vd2.setVisible(false);
            vd3.setVisible(false);
            new Perdeu().setVisible(true);
            dispose();
            }
        }
    }//GEN-LAST:event_tx6KeyReleased

    private void tx7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx7KeyReleased
        if (tx7.getText().equals("N")){
            tx7.setBackground(Color.green);
            tx8.setVisible(true);
            tx8.requestFocus();
        }else{
            tx7.setBackground(Color.red);
            tx7.requestFocus();
            erros +=1;
            if (erros == 1){
            vd1.setVisible(false);
            }
            else if (erros == 2){
            vd1.setVisible(false);
            vd2.setVisible(false);
            }
            else if (erros == 3){
            vd1.setVisible(false);
            vd2.setVisible(false);
            vd3.setVisible(false);
            new Perdeu().setVisible(true);
            dispose();
            }
        }
    }//GEN-LAST:event_tx7KeyReleased

    private void tx8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx8KeyReleased
        if (tx8.getText().equals("E")){
            tx8.setBackground(Color.green);
            new Ganhou().setVisible(true);
            dispose();
        }else{
            tx8.setBackground(Color.red);
            tx8.requestFocus();
            erros +=1;
            if (erros == 1){
            vd1.setVisible(false);
            }
            else if (erros == 2){
            vd1.setVisible(false);
            vd2.setVisible(false);
            }
            else if (erros == 3){
            vd1.setVisible(false);
            vd2.setVisible(false);
            vd3.setVisible(false);
            new Perdeu().setVisible(true);
            dispose();
            }
        }
    }//GEN-LAST:event_tx8KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jogoquatro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jogoquatro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jogoquatro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jogoquatro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jogoquatro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    private org.edisoncor.gui.panel.PanelImage panelImage3;
    private javax.swing.JFormattedTextField tx1;
    private javax.swing.JFormattedTextField tx2;
    private javax.swing.JFormattedTextField tx3;
    private javax.swing.JFormattedTextField tx4;
    private javax.swing.JFormattedTextField tx5;
    private javax.swing.JFormattedTextField tx6;
    private javax.swing.JFormattedTextField tx7;
    private javax.swing.JFormattedTextField tx8;
    private org.edisoncor.gui.panel.PanelImage vd1;
    private org.edisoncor.gui.panel.PanelImage vd2;
    private org.edisoncor.gui.panel.PanelImage vd3;
    // End of variables declaration//GEN-END:variables
}
